name: Deploy Android App to Firebase App Distribution

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/android/**'
      - '.github/workflows/android-firebase-distribution.yml'

jobs:
  build-and-distribute:
    name: Build and Distribute Android App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x apps/android/gradlew

    - name: Decode google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo $GOOGLE_SERVICES_JSON | base64 -d > apps/android/app/google-services.json

    - name: Create local.properties
      env:
        LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      run: |
        echo $LOCAL_PROPERTIES | base64 -d > apps/android/local.properties

    - name: Build Release APK
      run: |
        cd apps/android
        ./gradlew assembleRelease

    - name: Build Release AAB
      run: |
        cd apps/android
        ./gradlew bundleRelease

    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        groups: testers
        file: apps/android/app/build/outputs/apk/release/app-release.apk
        releaseNotes: |
          🚀 New build from main branch
          
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          
          Changes:
          ${{ github.event.head_commit.message }}

    - name: Upload AAB as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-bundle
        path: apps/android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: apps/android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30

    - name: Clean up secrets
      if: always()
      run: |
        rm -f apps/android/app/google-services.json
        rm -f apps/android/local.properties